'use client';
import {useEffect,useState} from 'react';import type {Inquiry} from '../lib/backend';
type Item={id:string;module:string;slug:string;title:string;status:string;updated_at:string};type RecordRow={id:string;created_at:string;status:string;[key:string]:unknown};type Backoffice={items:Item[];enrollments:RecordRow[];orders:RecordRow[];certificates:RecordRow[]};
const tabs=['overview','inquiries','solutions','academy','resources','work','enrollments','orders','certificates','settings'];
export function AdminDashboard(){const [items,setItems]=useState<Inquiry[]|null>(null),[office,setOffice]=useState<Backoffice|null>(null),[password,setPassword]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[tab,setTab]=useState('overview'),[showCreate,setShowCreate]=useState(false);
async function load(){setLoading(true);const [a,b]=await Promise.all([fetch('/api/inquiries'),fetch('/api/admin/backoffice')]);if(a.ok){setItems((await a.json()).inquiries);if(b.ok){setOffice(await b.json());setError('')}else setError((await b.json()).error)}else{setItems(null);setOffice(null)}setLoading(false)}useEffect(()=>{load()},[]);
async function login(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(!r.ok){setError((await r.json()).error);return}setPassword('');load()}
async function update(table:string,id:string,status:string){await fetch(table==='inquiries'?'/api/inquiries':'/api/admin/backoffice',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({table,id,status})});load()}
async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const body={type:tab==='certificates'?'certificate':tab==='enrollments'?'enrollment':'order',...Object.fromEntries(new FormData(form).entries())};const r=await fetch('/api/admin/backoffice',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(r.ok){setShowCreate(false);load()}else setError((await r.json()).error)}
if(loading)return <div className="admin-card"><p>Loading secure workspace…</p></div>;
if(!items)return <form className="admin-card admin-login" onSubmit={login}><img src="/brand/upstride-logo.png" alt="UPSTRIDE"/><small>SECURE ADMIN</small><h1>Welcome back.</h1><p>Enter the admin password configured in Vercel.</p>{error&&<div className="error">{error}</div>}<label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoFocus/></label><button className="btn">Open dashboard</button></form>;
const catalog=office?.items.filter(x=>x.module===tab)||[];const operational=tab==='enrollments'?office?.enrollments:tab==='orders'?office?.orders:office?.certificates;
return <div className="backoffice"><aside className="admin-nav"><img src="/brand/upstride-logo.png" alt="UPSTRIDE"/><small>BACK OFFICE</small>{tabs.map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x.replaceAll('-',' ')}</button>)}<button className="signout" onClick={async()=>{await fetch('/api/admin/login',{method:'DELETE'});setItems(null)}}>Sign out</button></aside><div className="admin-content"><header><div><small>UPSTRIDE ADMIN</small><h1>{tab.replaceAll('-',' ')}</h1></div>{['enrollments','orders','certificates'].includes(tab)&&<button className="btn small" onClick={()=>setShowCreate(true)}>+ Add record</button>}</header>{error&&<div className="error">{error}</div>}
{tab==='overview'&&<Overview inquiries={items} office={office}/>} {tab==='inquiries'&&<Inquiries rows={items} update={update}/>} {['solutions','academy','resources','work'].includes(tab)&&<Catalog rows={catalog} update={update}/>} {['enrollments','orders','certificates'].includes(tab)&&<Operations type={tab} rows={operational||[]} update={update}/>} {tab==='settings'&&<Settings/>}
{showCreate&&<CreateModal type={tab} close={()=>setShowCreate(false)} submit={create}/>}</div></div>}
function Overview({inquiries,office}:{inquiries:Inquiry[];office:Backoffice|null}){const stats=[['New inquiries',inquiries.filter(x=>x.status==='new').length],['Active programs',office?.items.filter(x=>x.module==='academy'&&x.status==='published').length||0],['Enrollments',office?.enrollments.length||0],['Resource orders',office?.orders.length||0],['Certificates',office?.certificates.length||0],['Published items',office?.items.filter(x=>x.status==='published').length||0]];return <><div className="stat-grid">{stats.map(x=><div key={x[0]}><strong>{x[1]}</strong><span>{x[0]}</span></div>)}</div><div className="admin-card wide"><h2>Back-office access</h2><p>Manage customer inquiries, catalog publishing states, learners, orders and certificate records from the navigation. Public content editing can be connected to these records as the next CMS phase.</p></div></>}
function Inquiries({rows,update}:{rows:Inquiry[];update:(t:string,i:string,s:string)=>void}){return <div className="admin-list">{rows.length===0?<Empty text="No inquiries yet."/>:rows.map(x=><article className="lead" key={x.id}><div><Badge value={x.status}/><small>{new Date(x.created_at).toLocaleString()}</small></div><h2>{x.name}</h2><a href={`mailto:${x.email}`}>{x.email}</a><p><b>{x.company||'No company'}</b> · {x.interest}</p><p>{x.message}</p><div className="lead-meta"><span>{x.budget||'No budget'}</span><span>{x.timeline||'No timeline'}</span><Status value={x.status} options={['new','contacted','qualified','closed']} onChange={s=>update('inquiries',x.id,s)}/></div></article>)}</div>}
function Catalog({rows,update}:{rows:Item[];update:(t:string,i:string,s:string)=>void}){return <div className="module-table">{rows.map(x=><div key={x.id}><div><Badge value={x.status}/><h3>{x.title}</h3><small>/{x.module}/{x.slug}</small></div><Status value={x.status} options={['draft','published','archived']} onChange={s=>update('backoffice_items',x.id,s)}/></div>)}</div>}
function Operations({type,rows,update}:{type:string;rows:RecordRow[];update:(t:string,i:string,s:string)=>void}){const table=type==='orders'?'resource_orders':type;const opts=type==='enrollments'?['pending','active','completed','cancelled']:type==='orders'?['pending','paid','fulfilled','refunded']:['valid','revoked'];return <div className="module-table">{rows.length===0?<Empty text={`No ${type} yet.`}/>:rows.map(x=><div key={x.id}><div><Badge value={x.status}/><h3>{String(x.learner_name||x.customer_name||x.certificate_id)}</h3><small>{String(x.program||x.resource||x.email||'')}</small></div><Status value={x.status} options={opts} onChange={s=>update(table,x.id,s)}/></div>)}</div>}
function Status({value,options,onChange}:{value:string;options:string[];onChange:(s:string)=>void}){return <select value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select>}function Badge({value}:{value:string}){return <span className={`lead-status ${value}`}>{value}</span>}function Empty({text}:{text:string}){return <div className="admin-card wide"><h2>{text}</h2><p>Records will appear here when they are created.</p></div>}
function CreateModal({type,close,submit}:{type:string;close:()=>void;submit:(e:React.FormEvent<HTMLFormElement>)=>void}){return <div className="modal"><form className="admin-card" onSubmit={submit}><button type="button" className="modal-close" onClick={close}>×</button><small>NEW {type.slice(0,-1).toUpperCase()}</small><h2>Add record</h2>{type==='certificates'?<><label>Certificate ID<input name="certificate_id" required placeholder="UPA-2026-0001"/></label><label>Learner name<input name="learner_name" required/></label><label>Program<input name="program" required/></label><label>Completion date<input type="date" name="completion_date" required/></label><input type="hidden" name="status" value="valid"/></>:type==='enrollments'?<><label>Learner name<input name="learner_name" required/></label><label>Email<input type="email" name="email" required/></label><label>Program<input name="program" required/></label><label>Package<input name="package" placeholder="Basic / Pro / Mentored"/></label><input type="hidden" name="status" value="pending"/></>:<><label>Customer name<input name="customer_name" required/></label><label>Email<input type="email" name="email" required/></label><label>Resource<input name="resource" required/></label><label>Amount<input type="number" name="amount" min="0"/></label><input type="hidden" name="status" value="pending"/></>}<button className="btn">Save record</button></form></div>}
function Settings(){return <div className="settings-grid"><div className="admin-card wide"><h2>Website settings</h2><p>Brand: UPSTRIDE<br/>Tagline: Your Next Step Forward.<br/>Philosophy: We Build. We Teach. We Provide.</p></div><div className="admin-card wide"><h2>Integrations</h2><p><b>Supabase</b> · Database and records<br/><b>Vercel</b> · Hosting and secure environment variables<br/><b>Email / CRM</b> · Ready for future connection</p></div><div className="admin-card wide"><h2>Security</h2><p>Admin access uses a secure HTTP-only session. Rotate ADMIN_PASSWORD, ADMIN_SECRET and the Supabase secret in Vercel whenever access changes.</p></div></div>}
