'use client';
import {useMemo,useState} from 'react';
import Link from 'next/link';

type Niche={code:string;name:string;course:string;slug:string;summary:string;reasons:string[];questions:string[]};
const niches:Niche[]=[
{code:'AUT',name:'Business Automation',course:'Business Automation Specialist',slug:'business-automation',summary:'You are drawn to making repetitive work simpler, more reliable and easier to manage.',reasons:['You notice inefficient steps and repeated handoffs.','You enjoy logic, structure and process improvement.','You are comfortable testing systems and handling exceptions.'],questions:['I enjoy finding repeated work that could be streamlined.','I naturally organize work into triggers, rules and actions.','I like improving processes even when the result is behind the scenes.','Testing whether a workflow works reliably sounds satisfying.']},
{code:'ECM',name:'E-Commerce',course:'E-Commerce Specialist',slug:'e-commerce',summary:'You combine customer curiosity with an interest in products, stores and commercial operations.',reasons:['You think about why customers choose one offer over another.','You can balance promotion with operational detail.','You enjoy improving an entire buying journey.'],questions:['I am curious about why people choose one product or store over another.','I enjoy organizing products, offers, pricing and buying journeys.','I can balance creative promotion with operational details.','Building and improving an online store feels exciting to me.']},
{code:'WEB',name:'Website Development',course:'Website Development Specialist',slug:'website-development',summary:'You enjoy turning ideas into useful, credible and well-structured digital experiences.',reasons:['You notice design, navigation and usability details.','You are interested in both creativity and technical construction.','You value visible work that people can immediately use.'],questions:['I enjoy turning a blank page into an organized digital experience.','I am interested in both design decisions and technical construction.','I notice confusing navigation, spacing or mobile layouts.','I would enjoy building something people can immediately visit and use.']},
{code:'AIB',name:'AI for Business',course:'AI for Business Specialist',slug:'ai-for-business',summary:'You want to explore intelligent tools while applying judgment, testing and responsible controls.',reasons:['You experiment while questioning limitations.','You can turn complex goals into clear instructions.','You enjoy evaluating quality, not only generating output.'],questions:['I enjoy experimenting with new tools while questioning their limitations.','I can explain a complex idea through clear instructions and examples.','Evaluating output quality sounds as interesting as generating it.','I want to design responsible AI workflows for practical business use.']},
{code:'LDG',name:'Lead Generation',course:'Lead Generation Specialist',slug:'lead-generation',summary:'You are energized by audiences, offers and creating a path from attention to qualified demand.',reasons:['You are curious about what motivates people to act.','You enjoy persuasive communication and testing.','You want to connect marketing activity to measurable opportunities.'],questions:['I enjoy understanding what motivates a specific audience to act.','Writing and testing offers or campaign messages appeals to me.','I like using evidence to improve response and conversion.','Connecting attention to a qualified sales conversation sounds rewarding.']},
{code:'SOC',name:'Social Media Systems',course:'Social Media Systems Specialist',slug:'social-media-systems',summary:'You enjoy turning ideas into consistent content and connecting conversation to business goals.',reasons:['You naturally see content possibilities in everyday ideas.','You care about tone, audience reaction and culture.','You can combine creative work with repeatable planning.'],questions:['I regularly think about how an idea could become engaging content.','I enjoy planning themes, formats, calendars and publishing routines.','I notice tone, audience reactions and platform culture.','I would enjoy connecting content activity to a business goal.']},
{code:'EML',name:'Email Marketing & Automation',course:'Email Marketing & Automation Specialist',slug:'email-marketing-automation',summary:'You appreciate timely writing, customer journeys and the logic behind relevant communication.',reasons:['You enjoy guiding people with useful messages.','You think in sequences, segments and timing.','You value both communication quality and performance data.'],questions:['I enjoy writing messages that guide people toward a useful next step.','I think naturally about timing, sequence, segments and behavior.','Testing subject lines and journey performance interests me.','I value permission and relevance in customer communication.']},
{code:'CRM',name:'CRM & Client Management',course:'CRM & Client Management Specialist',slug:'crm-client-management',summary:'You want relationships, commitments and next actions to remain organized and visible.',reasons:['You care about reliable information and clear ownership.','You enjoy follow-through and service consistency.','You naturally organize stages, records and next steps.'],questions:['I like keeping relationships, commitments and next steps organized.','I care about accurate information and clear ownership.','Designing stages, fields and follow-up rules feels natural to me.','I enjoy helping teams deliver a consistent client experience.']},
{code:'OPS',name:'Digital Business Operations',course:'Digital Business Operations Specialist',slug:'digital-business-operations',summary:'You see the whole organization and want people, processes, data and tools to work together.',reasons:['You notice how different teams affect one another.','You enjoy clarifying roles, standards and handoffs.','You balance big-picture thinking with practical detail.'],questions:['I naturally look at how different teams and tools affect one another.','I enjoy clarifying roles, handoffs, standards and documentation.','I can balance the big picture with practical operating details.','Improving an end-to-end service sounds more rewarding than optimizing one task.']}
];
const questions=niches.flatMap(n=>n.questions.map((text,i)=>({niche:n.code,text,number:i+1})));

export function NicheAssessment(){
 const [stage,setStage]=useState<'login'|'intro'|'questions'|'results'>('login');
 const [name,setName]=useState('');const [email,setEmail]=useState('');const [index,setIndex]=useState(0);const [answers,setAnswers]=useState<Record<number,number>>({});
 const current=questions[index];
 const top=useMemo(()=>niches.map(n=>({...n,score:questions.reduce((sum,q,i)=>q.niche===n.code?sum+(answers[i]||0):sum,0)})).sort((a,b)=>b.score-a.score).slice(0,3),[answers]);
 function login(e:React.FormEvent){e.preventDefault();setStage('intro')}
 function choose(value:number){const next={...answers,[index]:value};setAnswers(next);if(index===questions.length-1)setStage('results');else setIndex(index+1)}
 return <main className="assessment-page">
  <section className="assessment-brand"><small>UPSTRIDE ACADEMY</small><Link href="/">Exit assessment</Link></section>
  {stage==='login'&&<section className="assessment-gate"><div className="assessment-copy"><span>FREE DIGITAL NICHE ASSESSMENT</span><h1>Find the digital work that fits you.</h1><p>Answer 36 practical reflection questions and receive your top three digital niche recommendations, why they fit, and the courses that can help you begin.</p><ul><li>Approximately 8–10 minutes</li><li>Top three personalized pathways</li><li>Course recommendations by email</li></ul></div><form className="assessment-login" onSubmit={login}><small>SECURE YOUR RESULT</small><h2>Start with your email</h2><p>Your result will be connected to this email so you can return to it later.</p><label>Full name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your full name" required/></label><label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" required/></label><label className="assessment-consent"><input type="checkbox" required/> <span>I agree to receive my assessment result and relevant Upstride Academy course information by email.</span></label><button className="btn" type="submit">Continue securely →</button><em>Review mode: email verification and delivery activate after approval.</em></form></section>}
  {stage==='intro'&&<section className="assessment-intro"><small>BEFORE YOU ANSWER</small><h1>Choose from experience, not aspiration.</h1><p>This is not an intelligence test and there are no “better” niches. Rate what feels true for you today. Your results can change as you learn and gain experience.</p><div className="assessment-lenses"><div><b>ENERGY</b><span>What kind of work holds your attention?</span></div><div><b>STRENGTH</b><span>How do you naturally solve problems?</span></div><div><b>VALUE</b><span>What outcome would you enjoy creating?</span></div><div><b>ENVIRONMENT</b><span>Which working style helps you perform?</span></div></div><button className="btn" onClick={()=>setStage('questions')}>Begin the assessment →</button></section>}
  {stage==='questions'&&<section className="assessment-question"><div className="assessment-progress"><span>QUESTION {index+1} OF {questions.length}</span><b>{Math.round((index/questions.length)*100)}% COMPLETE</b><i><u style={{width:`${(index/questions.length)*100}%`}}/></i></div><small>{niches.find(n=>n.code===current.niche)?.name.toUpperCase()}</small><h1>{current.text}</h1><p>How accurately does this describe you today?</p><div className="assessment-scale">{[[1,'Not like me'],[2,'A little'],[3,'Sometimes'],[4,'Often'],[5,'Very like me']].map(([v,label])=><button key={v} onClick={()=>choose(v as number)}><b>{v}</b><span>{label}</span></button>)}</div><div className="assessment-controls"><button disabled={index===0} onClick={()=>setIndex(i=>i-1)}>← Previous</button><button onClick={()=>{setAnswers({});setIndex(0)}}>Start over</button></div></section>}
  {stage==='results'&&<section className="assessment-results"><div className="result-head"><small>YOUR DIGITAL NICHE PROFILE</small><h1>{name}, here are your top three pathways.</h1><p>These recommendations are based on your current preferences. Use them as a learning direction, then test the fit through practical work.</p><div><b>RESULT FOR</b><span>{email}</span><em>Email preview ready</em></div></div><div className="result-grid">{top.map((n,i)=><article key={n.code} className={i===0?'primary':''}><span>#{i+1} MATCH</span><strong>{n.score}/20</strong><h2>{n.name}</h2><p>{n.summary}</p><h3>Why it fits</h3><ul>{n.reasons.map(r=><li key={r}>{r}</li>)}</ul><Link className="btn" href={`/academy/${n.slug}`}>Explore {n.course} →</Link></article>)}</div><div className="result-note"><b>How to choose among your three</b><p>Lead with the pathway whose daily work you are most willing to practice. Your second and third results can become supporting skills that make your primary niche more valuable.</p><button className="textlink" onClick={()=>{setAnswers({});setIndex(0);setStage('intro')}}>Retake assessment</button></div></section>}
 </main>
}
