export type ResourceSection={title:string;intro:string;points:string[];action:string};
export type ResourceContent={promise:string;audience:string[];outcomes:string[];sections:ResourceSection[];included:string[];course:{title:string;slug:string;reason:string};download?:string};

export const resourceContent:Record<string,ResourceContent>={
  'your-first-step-into-online-work':{
    promise:'A practical 10-page introduction to online work that helps beginners understand the opportunity before choosing a learning path.',
    audience:['Beginners exploring remote or freelance work','Career changers who need a realistic starting point','Employees building a future-ready digital skill'],
    outcomes:['Understand how online professionals create value','Compare common freelance payment models','Recognize the responsibilities behind flexible work','Prepare for the Digital Niche Assessment'],
    sections:[
      {title:'The online work economy',intro:'Online work is ordinary professional work delivered through digital channels. Businesses hire people to build websites, manage stores, improve processes, find customers, organize data and communicate with audiences.',points:['Remote employment, freelancing and small digital businesses are different paths','Clients pay for useful outcomes—not simply time spent online','A focused skill is easier to explain, practice and sell than a vague promise'],action:'List three business problems you would enjoy learning to solve.'},
      {title:'How freelancers are paid',intro:'Payment depends on the agreement, scope and type of value delivered. Beginners should understand the model before accepting work.',points:['Hourly work fits changing or support-based assignments','Fixed projects require clear deliverables, boundaries and revision rules','Retainers support recurring responsibilities and ongoing improvement','Milestones reduce risk on larger projects'],action:'Write a sample scope containing one outcome, three deliverables and two exclusions.'},
      {title:'The benefits—and the responsibility',intro:'Freelancing can provide flexibility, variety and access to global opportunities, but it also requires reliability, communication and continuous learning.',points:['Build portable skills and a body of evidence','Choose projects that match your strengths over time','Manage uncertainty, deadlines and client expectations professionally','Protect client information and avoid exaggerated claims'],action:'Choose one weekly learning schedule you can maintain for the next eight weeks.'},
      {title:'Choose a direction before buying a course',intro:'The best first course matches both your natural working style and the problems you want to solve. The assessment compares your answers across ten digital pathways.',points:['Answer honestly rather than choosing what sounds impressive','Use the top three matches as options, not permanent labels','Read the explanation for each match before deciding','Choose one primary path and keep one adjacent skill for later'],action:'Take the free assessment and review all three recommended paths.'}
    ],included:['10-page downloadable eBook','Beginner reflection prompts','Freelance payment model guide','Direct assessment pathway'],course:{title:'Digital Niche Assessment',slug:'/digital-niche-assessment',reason:'Start here to identify your top three course pathways.'},download:'/UPSTRIDE-Your-First-Step-Into-Online-Work.pdf'
  },
  'template-library':{
    promise:'A starter library of reusable business documents that turns unclear requests into organized, reviewable work.',
    audience:['Freelancers preparing for client work','Students building portfolio projects','Small teams standardizing delivery'],
    outcomes:['Capture a useful brief','Control scope and decisions','Report progress clearly','Hand work over professionally'],
    sections:[
      {title:'Discovery brief',intro:'A good project begins with the business problem, desired outcome, audience, constraints and evidence—not a premature tool choice.',points:['Stakeholders and decision owner','Current situation and desired future state','Constraints, assumptions and open questions','Success measures and acceptance criteria'],action:'Complete the brief using a real or simulated business problem.'},
      {title:'Scope and requirements',intro:'Scope protects both sides by translating an idea into work that can be inspected and accepted.',points:['In-scope deliverables','Explicit exclusions','Dependencies and client responsibilities','Change-request and approval process'],action:'Ask another person to review the scope and identify one ambiguity.'},
      {title:'Status and decision log',intro:'Professional updates make progress, risk and required decisions visible before a deadline is threatened.',points:['Completed, next and blocked work','Decision, options, owner and due date','Risk, impact and proposed response','Evidence or links needed for review'],action:'Write a five-sentence status update for a delayed project.'},
      {title:'Handoff and retrospective',intro:'Delivery is complete only when another person can understand, operate and maintain the work.',points:['Access and ownership record','Operating instructions and known limitations','Test evidence and unresolved items','Lessons learned and next improvements'],action:'Create a handoff checklist for your strongest portfolio project.'}
    ],included:['Discovery brief','Project scope canvas','Requirements register','Status update template','Decision and risk log','Client handoff checklist'],course:{title:'Digital Business Operations Specialist',slug:'/academy/digital-business-operations-specialist',reason:'Learn how these templates support reliable end-to-end operations.'}
  },
  'sop-collection':{
    promise:'A practical system for writing procedures people can follow, verify and improve—not documents that collect dust.',
    audience:['Operations assistants and coordinators','Automation and CRM specialists','Founders documenting recurring work'],
    outcomes:['Select the right process to document','Write usable steps and decisions','Add quality and exception controls','Maintain ownership and version history'],
    sections:[
      {title:'Select the right process',intro:'Document work that is repeated, important, error-prone or dependent on one person.',points:['Define the trigger and completion condition','Identify user, frequency and business risk','Observe the real process before writing','Separate policy from step-by-step procedure'],action:'Score three processes by frequency, impact and error risk.'},
      {title:'Write for execution',intro:'Each step should tell the user what to do, where to do it and what successful completion looks like.',points:['Use one clear action per step','Name fields, records and expected outputs','Add screenshots only when they clarify a decision','Link supporting templates and definitions'],action:'Rewrite one vague instruction into an observable action and result.'},
      {title:'Control quality and exceptions',intro:'A useful SOP explains normal work and what to do when reality differs from the happy path.',points:['Pre-flight and completion checks','Common failure signals','Escalation threshold and owner','Recovery, rollback or correction steps'],action:'Add two likely exceptions and an escalation rule to your procedure.'},
      {title:'Publish and maintain',intro:'Procedures need an owner, review rhythm and feedback loop to remain trustworthy.',points:['Version, effective date and owner','Change log and approval record','Scheduled review or event-based update','Simple feedback channel for users'],action:'Assign an owner and next review date to the SOP.'}
    ],included:['SOP master template','Process observation worksheet','Quality-control checklist','Exception and escalation table','Version history template'],course:{title:'Business Automation Specialist',slug:'/academy/business-automation-specialist',reason:'Build the workflows that your SOPs describe and control.'}
  },
  'ai-prompt-pack':{
    promise:'A responsible prompt system for producing clearer drafts, analysis and operational support with human review built in.',
    audience:['Business owners adopting AI','Assistants and digital specialists','Teams creating repeatable AI-supported workflows'],
    outcomes:['Write structured prompts','Provide appropriate context','Evaluate outputs systematically','Protect sensitive information'],
    sections:[
      {title:'Use a complete prompt brief',intro:'Strong prompts define the role, objective, context, inputs, constraints, output format and quality standard.',points:['State the real task and intended user','Provide only relevant, permitted context','Specify format, tone and limits','Request assumptions and uncertainties explicitly'],action:'Rewrite a one-line request using all seven prompt elements.'},
      {title:'Work in stages',intro:'Complex work improves when research, analysis, drafting and review are separated.',points:['Ask for missing information first','Generate options before selecting','Critique against an explicit rubric','Revise using identified gaps'],action:'Turn one complex request into a four-stage prompt sequence.'},
      {title:'Verify before use',intro:'Fluent output can still be wrong. Human review is required when work affects customers, money, access, reputation or rights.',points:['Check facts against authoritative sources','Test calculations and links','Review bias, tone and unsupported claims','Record the reviewer and approval status'],action:'Create a verification checklist for an AI-generated client report.'},
      {title:'Protect people and data',intro:'Never paste secrets, unnecessary personal data or confidential client information into an unapproved AI service.',points:['Minimize or anonymize inputs','Follow the organization’s approved-tool policy','Keep final accountability with a person','Escalate high-impact or uncertain decisions'],action:'Redact a sample customer record while preserving the information needed for the task.'}
    ],included:['Seven-part prompt brief','Analysis prompt sequence','Content review rubric','Data-safety checklist','Prompt improvement log'],course:{title:'AI for Business Specialist',slug:'/academy/ai-for-business-specialist',reason:'Learn to design useful, governed AI workflows for real business needs.'}
  },
  'growth-checklists':{
    promise:'A focused set of checks for finding the weakest point in a customer journey before spending more on traffic or tools.',
    audience:['Founders planning growth','Marketing and lead-generation assistants','Commerce and website specialists'],
    outcomes:['Audit the full customer journey','Identify evidence-backed bottlenecks','Choose a focused experiment','Measure learning without fake certainty'],
    sections:[
      {title:'Offer and audience clarity',intro:'Growth begins with a specific customer, urgent problem, credible promise and clear next step.',points:['Audience and situation are specific','Offer explains the useful outcome','Proof is accurate and appropriately labeled','Call to action matches buyer readiness'],action:'Explain the offer in one sentence without jargon.'},
      {title:'Acquisition and message',intro:'Review whether the right people encounter a message that earns attention and creates qualified interest.',points:['Channel matches audience behavior','Message connects problem, value and evidence','Campaign uses consistent tracking','Lead definition protects quality'],action:'Create one message hypothesis and the evidence that would support it.'},
      {title:'Conversion and follow-up',intro:'Inspect the transition from interest to action across page, form, response and booking.',points:['Page answers the visitor’s core questions','Form collects only necessary information','Response time and ownership are defined','Follow-up helps rather than pressures'],action:'Walk through the journey on a phone and record every friction point.'},
      {title:'Retention and learning',intro:'Sustainable growth includes delivery quality, repeat use, referrals and disciplined experimentation.',points:['Customer expectations match delivery','Lifecycle messages remain relevant','Metric definitions are consistent','Experiments change one important variable at a time'],action:'Select one bottleneck, one change and one decision rule for a two-week test.'}
    ],included:['Growth journey audit','Landing-page review','Lead-quality checklist','Experiment card','Weekly metrics review'],course:{title:'Lead Generation Specialist',slug:'/academy/lead-generation-specialist',reason:'Develop a measurable system from audience research to qualified conversation.'}
  },
  'client-toolkit':{
    promise:'A professional operating kit for stronger discovery, communication, delivery and handoff throughout a client engagement.',
    audience:['New and developing freelancers','Specialists managing client projects','Small service teams improving client experience'],
    outcomes:['Run better discovery conversations','Set expectations early','Handle changes professionally','Close projects with usable evidence'],
    sections:[
      {title:'Qualify the engagement',intro:'A good-fit project has a meaningful problem, an available decision maker, realistic constraints and a service you can responsibly deliver.',points:['Business need and urgency','Stakeholders and decision process','Budget and timeline expectations','Capability fit and ethical boundaries'],action:'Write five questions that reveal fit without turning the call into an interrogation.'},
      {title:'Agree on the work',intro:'Confirm deliverables, responsibilities, communication rhythm, access, approvals and the method for handling change.',points:['Deliverables and acceptance criteria','Client inputs and access deadlines','Meeting and update cadence','Revision and change-control rules'],action:'Draft a kickoff summary that a client can approve in writing.'},
      {title:'Communicate through difficulty',intro:'Clients need early clarity when assumptions fail, inputs are late or technical problems appear.',points:['Describe facts without blame','Explain impact in business language','Offer realistic options and recommendation','Record the decision and new expectation'],action:'Write a delay update with two options and one recommendation.'},
      {title:'Deliver, prove and continue',intro:'A strong close demonstrates what was completed, how it was verified, what remains and how the client can operate it.',points:['Acceptance evidence and demonstration','Ownership, credentials and documentation','Known limitations and support boundary','Ethical next-step recommendation'],action:'Prepare a five-minute handoff agenda for a portfolio project.'}
    ],included:['Discovery call guide','Kickoff agenda','Client update templates','Change request form','Feedback and approval record','Handoff checklist'],course:{title:'Digital Solutions Specialist',slug:'/academy/digital-solutions-specialist',reason:'Practice complete client discovery, solution delivery and professional handoff.'}
  }
};
